// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zododyqzfagncobwqqaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvZG9keXF6ZmFnbmNvYndxcWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODg3NDMsImV4cCI6MjA2NDQ2NDc0M30.zWXwd3a4vB1502D_mJFv54ZiMITWhiDnS8DF5PDXhwE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);